#!/usr/bin/env python3

## laymix - utility to mix image layers into all possible results
## Copyright (c) 2021 moonburnt
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see https://www.gnu.org/licenses/gpl-3.0.txt

import argparse
import laymix
from os.path import join
from sys import exit
import logging

SAVEDIR = join(".", "results")
IMGDIR = join(".", "images")

log = logging.getLogger()
log.setLevel(logging.INFO)
handler = logging.StreamHandler()
formatter = logging.Formatter(
    fmt="[%(asctime)s][%(name)s][%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
handler.setFormatter(formatter)
log.addHandler(handler)

ap = argparse.ArgumentParser()
ap.add_argument(
    "items",
    nargs="*",
    help=(
        "Path(s) to process images from. If not set - will use "
        f"default path, which is {IMGDIR}"
    ),
)
ap.add_argument(
    "--savedir",
    help=(f"Directory to save results into. Default: {SAVEDIR}"),
)
ap.add_argument(
    "--prefixes",
    nargs="+",
    help=(
        "Prefixes used to split received images into layer groups."
        "Mask isnt regexp, but text that should be in file name."
    ),
    required="True",
)
ap.add_argument(
    "--include-background",
    action="store_true",
    help=(
        "If enabled, backgrounds will be also threated as 1st "
        "layer and added into constructors. Default = False"
    ),
)
ap.add_argument(
    "--debug",
    action="store_true",
    help="Show debug messages in log",
)
args = ap.parse_args()
# TODO: maybe add ability to specify layer's files manually

if args.debug:
    log.setLevel(logging.DEBUG)

# TODO: add ability to specify prefixes in some sort of config file
prefixes = args.prefixes
log.debug(f"Got following prefixes to parse: {prefixes}")

mixer = laymix.LayerMixer(
    prefixes=prefixes,
    savedir=(args.savedir or SAVEDIR),
)
items = args.items or [IMGDIR]

files = []
for item in items:
    valid_files = mixer.get_files(item)
    files.extend(valid_files)

if not files:
    log.critical("Got no images! Run this tool with -h arg to find how to use it")
    exit(1)

log.info("Sorting images into layer groups by filenames")
constructors = mixer.make_constructors(
    files=files,
    include_background=args.include_background,
)

if not constructors:
    log.critical("None of provided images match provided prefixes!")
    exit(1)

log.info("Building images (it may take some time)")
for item in constructors:
    imgs = mixer.build_images(item)
    mixer.save(
        images=imgs,
        name_mask=item.name,
    )

log.info("Done")
